import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { execFileSync } from 'node:child_process';
const file = fs.readdirSync('.').find(f => f.endsWith('.html'));
const html = fs.readFileSync(file, 'utf8');
const unpack = (s,type) => JSON.parse(s.match(new RegExp(`<script type="__bundler/${type}">\\s*([\\s\\S]*?)\\s*</script>`))[1]);
const template = unpack(html,'template');
assert.deepEqual(unpack(html,'manifest'), unpack(execFileSync('git',['show',`HEAD:${file}`],{encoding:'utf8',maxBuffer:30e6}),'manifest'));
const logic = template.slice(template.indexOf('const STORAGE_KEY'),template.lastIndexOf('</script>'));
let fetched = 0, writes = 0, reveals = 0, complete;
class Base { props={guestPasscode:'TEST', organiserPassword:'ADMIN'}; setState(update,cb){this.state={...this.state,...(typeof update==='function'?update(this.state):update)};cb?.();} }
const context = { DCLogic:Base,React:{createRef:()=>({})},localStorage:{getItem:()=>null,setItem:()=>{writes++;}},setInterval:()=>1,clearInterval(){},setTimeout:()=>1,clearTimeout(){},requestAnimationFrame:cb=>cb(),document:{getElementById:()=>null},URLSearchParams,window:{location:{search:''},InvitationAccess:{resolve:async code=>code==='TEST'?'both':null},matchMedia:()=>({matches:true}),InvitationEffects:{reveal:(_el,cb)=>{reveals++;complete=cb;}}},fetch:async()=>{fetched++;return {ok:true,json:async()=>[]};} };
vm.createContext(context); vm.runInContext(logic+'\nthis.Component=Component;', context);
const component = new context.Component();
component.props.supabaseUrl='https://example.invalid';component.props.supabaseAnonKey='test';
component.componentDidMount(); await component.refreshResponses(); assert.equal(fetched,0,'No pre-unlock RSVP fetch');
assert.equal(component.renderVals().isInvite,false);
component.state.gateInput='wrong';await component.submitGate();assert.equal(reveals,0);assert.ok(component.state.gateError);
component.state.gateInput='TEST';await Promise.all([component.submitGate(),component.submitGate()]);assert.equal(reveals,1);complete();
assert.equal(component.state.unlocked,true);assert.equal(component.state.gateInput,'');assert.equal(component.renderVals().showContent,false);
component.state.adminInput='ADMIN';component.submitAdmin(); await Promise.resolve();assert.equal(fetched,1);await Promise.resolve();await Promise.resolve();
component.props.supabaseUrl='';component.state.form={...component.blankForm(),name:'Test',attending:'yes'};
await component.submitForm();assert.ok(component.state.formError);assert.equal(writes,0);
component.state.form.attendWedding=true;await component.submitForm();await component.submitForm();assert.equal(writes,1);assert.equal(component.state.responses.length,1);
component.resetForm();component.props.supabaseUrl='https://example.invalid';component.state.form={...component.blankForm(),name:'Test',attending:'no'};
let resolveFetch;context.fetch=()=>{fetched++;return new Promise(resolve=>{resolveFetch=resolve;});};
const sending=component.submitForm();const fetchCount=fetched;await component.submitForm();assert.equal(fetched,fetchCount);
resolveFetch({ok:false});await sending;assert.equal(component.sending,false);assert.match(component.state.formError,/Could not save/);
console.log('PASS: bundled assets preserved, controller parses, gate isolation, invalid/valid entry, repeated entry, no pre-unlock fetch, organiser refresh, RSVP validation, local duplicate guard, network duplicate/failure handling');
const effectSource=fs.readFileSync('assets/invitation.js','utf8');
let created=0,finished=0,removed=0,raf,timeoutId=0;
const motion={matches:true,addEventListener(){},removeEventListener(){}};
const ctx=new Proxy({}, {get:()=>()=>{},set:()=>true});
const env={window:{},matchMedia:()=>motion,innerWidth:390,innerHeight:844,devicePixelRatio:3,navigator:{hardwareConcurrency:4},requestAnimationFrame:cb=>{raf=cb;return 1;},cancelAnimationFrame(){},setTimeout:()=>++timeoutId,clearTimeout(){},localStorage:{setItem(){}},document:{createElement:()=>{created++;return {setAttribute(){},getContext:()=>ctx,remove(){removed++;}};},body:{append(){}},addEventListener(){},removeEventListener(){},querySelector:()=>null}};
vm.createContext(env);vm.runInContext(effectSource,env);
const gate={getBoundingClientRect:()=>({left:0,top:0,width:390,height:844}),querySelectorAll:()=>[],classList:{add(){}}};
env.window.InvitationEffects.reveal(gate,()=>finished++);assert.equal(created,0);assert.equal(finished,1);
motion.matches=false;env.window.InvitationEffects.reveal(gate,()=>finished++);env.window.InvitationEffects.reveal(gate,()=>finished++);assert.equal(created,1);raf(0);raf(3400);assert.equal(finished,2);assert.equal(removed,1);
console.log('PASS: reduced-motion skips canvas, repeated reveal allocates once, animation completes and cleans up');
let played=0, paused=0, resolvePlay, state=false;
env.Audio=class {paused=true;play(){played++;this.paused=false;return new Promise(r=>resolvePlay=r);} pause(){paused++;this.paused=true;}};
const music=env.window.InvitationMusic;assert.equal(played,0);
const play=music.play(on=>state=on);await music.play(on=>state=on);assert.equal(played,1);music.pause();resolvePlay();await play;assert.equal(state,false);assert.equal(music.isPlaying(),false);
console.log('PASS: no audio before initialization, duplicate play guarded, pause wins pending play race');
assert.ok(template.includes('USUAN2000015') && template.includes('https://creativecommons.org/licenses/by/4.0/'));
console.log('PASS: source-linked CC BY attribution and conversion notice included');
let handlers={};env.document.addEventListener=(name,cb)=>handlers[name]=cb;env.document.removeEventListener=name=>delete handlers[name];env.localStorage.getItem=()=>null;
music.init(on=>state=on);assert.equal(played,2,'Initialization attempts autoplay');resolvePlay();await new Promise(setImmediate);assert.equal(state,true);
music.pause();const mutedPlays=played;handlers.pointerdown({target:{closest:()=>false}});assert.equal(played,mutedPlays,'Explicit mute survives ordinary interactions');music.destroy();assert.equal(Object.keys(handlers).length,0);
assert.ok(template.includes('2027-01-09T14:45:00+05:30'));
assert.ok(template.includes('28 December 2026 · 11:30 AM'));
assert.ok(!template.includes('29 Dec, Kannur'));
console.log('PASS: autoplay attempt, remembered mute prevents gesture retry, event cleanup, corrected ceremony countdown and engagement date');
for (const kind of ['engagement','wedding','both']) {
 context.window.location.search='';
 const invite=new context.Component();context.window.InvitationAccess.resolve=async()=>kind;invite.state.gateInput='TEST';await invite.submitGate();complete();const vals=invite.renderVals();
 assert.equal(vals.showEngagement,kind!=='wedding');assert.equal(vals.showWedding,kind!=='engagement');
 assert.equal(invite.state.form.attendEngagement,kind==='engagement');assert.equal(invite.state.form.attendWedding,kind==='wedding');
 invite.state.form={...invite.blankForm(),name:'Test',attending:'yes',attendEngagement:true,attendWedding:true};
 await invite.submitForm();const response=invite.state.responses[0];
 assert.equal(response.attendEngagement,kind!=='wedding');assert.equal(response.attendWedding,kind!=='engagement');
}
context.window.location.search='?invite=unknown';assert.equal(new context.Component().inviteType,'both');
assert.ok(!template.includes('P. V. Bhaskaran'));assert.ok(!template.includes('A. P. K. Meenakshi'));assert.ok(!template.includes('guestPasscode'));
const {webcrypto,createHash}=await import('node:crypto');
const access={window:{},crypto:webcrypto,TextEncoder};vm.createContext(access);
const accessSource=fs.readFileSync('assets/invitation-access.js','utf8');
const testHashes=Object.fromEntries(['engagement','wedding','both'].map(kind=>[kind,createHash('sha256').update('TEST-'+kind).digest('hex')]));
vm.runInContext(accessSource.replace(/const hashes = [\s\S]*?;/,'const hashes = '+JSON.stringify(testHashes)+';'),access);
for (const kind of Object.keys(testHashes)) {
 assert.equal(await access.window.InvitationAccess.resolve('TEST-'+kind),kind);

}
assert.equal(await access.window.InvitationAccess.resolve('wrong'),null);
console.log('PASS: three variants, isolated event visibility/defaults, enforced RSVP scope, unknown-link fallback, passcode-selected views on one URL, removed blessing section');
assert.ok(!template.includes('class="experience-controls"'));
assert.ok(template.includes('Kindly reply by 15 November 2026'));
assert.ok(template.includes('Please RSVP by 15 November 2026 for catering.'));
assert.ok(!template.includes('15 December 2026'));
assert.ok(template.includes('/assets/engagement-church.jpeg'));
let waterFrame, waterRemoved=0, waterClears=0, waterEllipses=0, waterChange, waterEvents={}, waterNow=2000, impact, impacts=[];
const waterMotion={matches:false,addEventListener:(_n,fn)=>waterChange=fn,removeEventListener(){}};
const waterContext=new Proxy({}, {get:(_o,key)=>(key==='createLinearGradient'||key==='createRadialGradient')?()=>({addColorStop(){}}):key==='clearRect'?()=>waterClears++:key==='ellipse'?(x,y)=>{waterEllipses++;impact=[x,y];impacts.push([x,y]);}:()=>{},set:()=>true});
const waterEnv={Math:Object.assign(Object.create(Math),{random:()=>.9}),performance:{now:()=>waterNow},window:{},matchMedia:()=>waterMotion,devicePixelRatio:3,requestAnimationFrame:fn=>{waterFrame=fn;return 1;},cancelAnimationFrame(){},ResizeObserver:class{observe(){} disconnect(){}},document:{hidden:false,querySelector:()=>({clientWidth:390,clientHeight:844,getBoundingClientRect:()=>({left:0,top:0}),append(){}}),createElement:()=>({setAttribute(){},getContext:()=>waterContext,remove(){waterRemoved++;}}),addEventListener:(name,fn)=>waterEvents[name]=fn,removeEventListener:name=>delete waterEvents[name]}};
vm.createContext(waterEnv);vm.runInContext(fs.readFileSync('assets/watercolour.js','utf8'),waterEnv);
waterEnv.window.InvitationAtmosphere.start();waterFrame(50);waterFrame(1400);waterFrame(1600);
assert.ok(waterEllipses>0,'Natural falling drops produce ripples after landing');
waterEvents.pointerdown({type:'pointerdown',clientX:100,clientY:200});waterFrame(2800);waterFrame(2900);
assert.ok(Math.abs(impact[0]-100)<.001 && Math.abs(impact[1]-200)<.001);
waterNow=4300;waterEvents.pointermove({type:'pointermove',clientX:140,clientY:215});waterFrame(5100);waterFrame(5200);
assert.ok(!impacts.some(([x,y])=>Math.abs(x-140)<.01 && Math.abs(y-215)<.01),'Slow short movement cannot overlap an active bloom');
waterNow=5400;waterEvents.pointermove({type:'pointermove',clientX:330,clientY:210});waterFrame(6200);waterFrame(6300);
assert.ok(impacts.some(([x,y])=>Math.abs(x-330)<.01 && Math.abs(y-210)<.01),'Distant movement still creates a drop');
waterNow=8000;waterEvents.pointermove({type:'pointermove',clientX:103,clientY:203});waterFrame(8800);waterFrame(8900);
assert.ok(impacts.some(([x,y])=>Math.abs(x-103)<.01 && Math.abs(y-203)<.01),'The same area is available after its prior bloom fades');
waterMotion.matches=true;waterChange();assert.ok(waterClears>0);waterEnv.window.InvitationAtmosphere.stop();assert.equal(waterRemoved,1);
console.log('PASS: visible controls removed, consistent 15 November RSVP deadline, church artwork, drop-impact ripples and motion cleanup');
